#ifndef STATESET_UCP_H
#define STATESET_UCP_H

#pragma once

/* Auto-generated by cbindgen. Do not edit directly. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>

typedef struct UcpCheckoutService UcpCheckoutService;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void ucp_string_free(char *ptr);

struct UcpCheckoutService *ucp_checkout_service_new(const char *config_json, char **out_error);

void ucp_checkout_service_free(struct UcpCheckoutService *service);

char *ucp_checkout_create(struct UcpCheckoutService *service,
                          const char *request_json,
                          char **out_error);

char *ucp_checkout_get(struct UcpCheckoutService *service,
                       const char *checkout_id,
                       char **out_error);

char *ucp_checkout_update(struct UcpCheckoutService *service,
                          const char *checkout_id,
                          const char *request_json,
                          char **out_error);

char *ucp_checkout_complete(struct UcpCheckoutService *service,
                            const char *checkout_id,
                            const char *request_json,
                            char **out_error);

char *ucp_checkout_cancel(struct UcpCheckoutService *service,
                          const char *checkout_id,
                          char **out_error);

char *ucp_checkout_discovery_document(struct UcpCheckoutService *service, char **out_error);

char *ucp_crypto_generate_key_pair(const char *algorithm, const char *kid, char **out_error);

char *ucp_crypto_sign_json(const char *json_value, const char *jwk_private_json, char **out_error);

bool ucp_crypto_verify_json(const char *jws_compact,
                            const char *json_value,
                            const char *jwk_public_json,
                            char **out_error);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* STATESET_UCP_H */
