/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Configuration for CheckoutService */
export interface CheckoutServiceConfig {
  /** UCP protocol version */
  ucpVersion: string
  /** Service version */
  serviceVersion: string
  /** Base URL for the service */
  baseUrl: string
  /** Session TTL in seconds */
  sessionTtlSeconds: number
  /** Tax rate in basis points (e.g., 825 = 8.25%) */
  taxBps: number
  /** Enable identity linking capability */
  identityLinkingEnabled?: boolean
  /** Enable buyer consent capability */
  buyerConsentEnabled?: boolean
  /** Enable AP2 mandate capability */
  ap2Enabled?: boolean
  /** Static AP2 merchant authorization (optional) */
  ap2MerchantAuthorization?: string
}
/** Signing algorithm enumeration */
export const enum SigningAlgorithm {
  /** ECDSA with P-256 curve and SHA-256 */
  ES256 = 0,
  /** ECDSA with P-384 curve and SHA-384 */
  ES384 = 1
}
/** Detached JWS signature result */
export interface DetachedJws {
  /** Base64url encoded protected header */
  protected: string
  /** Base64url encoded signature */
  signature: string
}
/** Configuration for OrderService */
export interface OrderServiceConfig {
  /** UCP protocol version */
  ucpVersion: string
  /** Base URL used to construct order permalinks */
  baseUrl?: string
}
/** Node.js wrapper for the UCP CheckoutService */
export declare class CheckoutService {
  /** Creates a new CheckoutService instance */
  constructor(config: CheckoutServiceConfig)
  /**
   * Creates a new checkout session
   *
   * @param requestJson - JSON string of CheckoutCreateRequest
   * @returns JSON string of CheckoutResponse
   */
  createCheckout(requestJson: string): Promise<string>
  /**
   * Gets an existing checkout session by ID
   *
   * @param checkoutId - The checkout session ID
   * @returns JSON string of CheckoutResponse
   */
  getCheckout(checkoutId: string): Promise<string>
  /**
   * Updates an existing checkout session
   *
   * @param checkoutId - The checkout session ID
   * @param requestJson - JSON string of CheckoutUpdateRequest
   * @returns JSON string of CheckoutResponse
   */
  updateCheckout(checkoutId: string, requestJson: string): Promise<string>
  /**
   * Completes a checkout session and creates an order
   *
   * @param checkoutId - The checkout session ID
   * @param requestJson - JSON string of CheckoutCompleteRequest
   * @returns JSON string of CheckoutResponse
   */
  completeCheckout(checkoutId: string, requestJson: string): Promise<string>
  /**
   * Cancels a checkout session
   *
   * @param checkoutId - The checkout session ID
   * @returns JSON string of CheckoutResponse
   */
  cancelCheckout(checkoutId: string): Promise<string>
  /**
   * Returns the UCP discovery document
   *
   * @returns JSON string of DiscoveryDocument
   */
  discoveryDocument(): Promise<string>
}
/** Opaque handle to a signing key (private key) */
export declare class SigningKey {
  /** Returns the key ID */
  get kid(): string
  /** Returns the algorithm */
  get algorithm(): SigningAlgorithm
}
/** Opaque handle to a verifying key (public key) */
export declare class VerifyingKey {
  /** Returns the key ID */
  get kid(): string
  /** Returns the algorithm */
  get algorithm(): SigningAlgorithm
}
/** Crypto utilities for JWS signing and verification */
export declare class Crypto {
  /**
   * Canonicalizes a JSON value according to RFC 8785 (JCS)
   *
   * @param jsonValue - JSON string to canonicalize
   * @returns Canonical byte representation
   */
  static canonicalize(jsonValue: string): Buffer
  /**
   * Creates a detached JWS signature over the given payload
   *
   * @param payload - The payload bytes to sign
   * @param key - The signing key
   * @returns Detached JWS object
   */
  static signDetached(payload: Buffer, key: SigningKey): DetachedJws
  /**
   * Verifies a detached JWS signature
   *
   * @param jwsCompact - Compact JWS string (header..signature)
   * @param payload - The payload bytes that were signed
   * @param key - The verifying key
   * @throws Error if verification fails
   */
  static verifyDetached(jwsCompact: string, payload: Buffer, key: VerifyingKey): void
  /**
   * Signs a JSON value with canonicalization
   *
   * @param jsonValue - JSON string to sign
   * @param key - The signing key
   * @returns Detached JWS object
   */
  static signJson(jsonValue: string, key: SigningKey): DetachedJws
  /**
   * Verifies a JWS signature against a JSON value
   *
   * @param jwsCompact - Compact JWS string (header..signature)
   * @param jsonValue - JSON string that was signed
   * @param key - The verifying key
   * @throws Error if verification fails
   */
  static verifyJson(jwsCompact: string, jsonValue: string, key: VerifyingKey): void
  /**
   * Loads a signing key from a JWK with private key component
   *
   * @param jwkJson - JSON string of JWK with 'd' (private key) component
   * @returns SigningKey handle
   */
  static loadSigningKeyFromPrivate(jwkJson: string): SigningKey
  /**
   * Loads a verifying (public) key from a JWK
   *
   * @param jwkJson - JSON string of public JWK
   * @returns VerifyingKey handle
   */
  static loadVerifyingKey(jwkJson: string): VerifyingKey
  /**
   * Generates a new signing key for the given algorithm
   *
   * @param algorithm - The signing algorithm (ES256 or ES384)
   * @param kid - Key ID to assign to the generated key
   * @returns SigningKey (the verifying key can be derived from it)
   */
  static generateSigningKey(algorithm: SigningAlgorithm, kid: string): SigningKey
  /**
   * Generates a new key pair for signing and verification
   *
   * @param algorithm - The signing algorithm (ES256 or ES384)
   * @param kid - Key ID to assign to the generated keys
   * @returns Object with signingKey and verifyingKey properties
   */
  static generateKeyPair(algorithm: SigningAlgorithm, kid: string): { signingKey: SigningKey, verifyingKey: VerifyingKey }
  /**
   * Exports a verifying key to JWK format
   *
   * @param key - The verifying key to export
   * @returns JSON string of the public JWK
   */
  static exportVerifyingKeyJwk(key: VerifyingKey): string
  /**
   * Converts a DetachedJws to compact format (header..signature)
   *
   * @param jws - The DetachedJws object
   * @returns Compact JWS string
   */
  static jwsToCompact(jws: DetachedJws): string
  /**
   * Parses a compact JWS string into a DetachedJws object
   *
   * @param compact - Compact JWS string (header..signature)
   * @returns DetachedJws object
   */
  static jwsFromCompact(compact: string): DetachedJws
}
/**
 * Order service for post-checkout order lifecycle management
 *
 * Handles order retrieval, fulfillment events, and adjustments
 */
export declare class OrderService {
  /** Creates a new OrderService instance */
  constructor(config: OrderServiceConfig)
  /**
   * Gets an order by ID
   *
   * @param orderId - The order ID
   * @returns JSON string of Order
   */
  getOrder(orderId: string): Promise<string>
  /**
   * Adds a fulfillment event to an order
   *
   * @param orderId - The order ID
   * @param requestJson - JSON string of FulfillmentEventRequest
   * @returns JSON string of updated Order
   */
  addFulfillmentEvent(orderId: string, requestJson: string): Promise<string>
  /**
   * Adds an adjustment to an order (refund, return, credit, etc.)
   *
   * @param orderId - The order ID
   * @param requestJson - JSON string of AdjustmentRequest
   * @returns JSON string of updated Order
   */
  addAdjustment(orderId: string, requestJson: string): Promise<string>
  /**
   * Stores an order in the service's order store
   *
   * This is useful for testing or when orders are created externally
   *
   * @param orderJson - JSON string of Order
   */
  storeOrder(orderJson: string): Promise<void>
}
